### ISSUE TITLE
Example 1 - using provided datasets - Error

### ISSUE THREAD

**Issue by mgaynor1** [jasonleebrown/humboldt#1]
I am using R version 3.6.2 (2019-12-12) and ‘humboldt’ version 0.9.3.120618. I am attempting to run Example 1. The error I received is below. 

`Error in  tkProgressBar(title = "Initializing", label = "", min = 0, max = nPts,  : 
  could not find function "tkProgressBar"`

I tried to install tcltk - to make sure this wasn't the issue and got the following  message

`> install.packages("tcltk")
Warning in install.packages :
  package ‘tcltk’ is not available (for R version 3.6.2)
Warning in install.packages :
  package ‘tcltk’ is a base package, and should not be updated`

Any ideas?

**Comment by jasonleebrown** [comment]
I just installed the latest version of R and installed everything and ran, example one without issues.  I think you are on to your issue - with 'tcltk' not being installed properly. Try manually installing it and any other package that do not install during installation. If you have any issues, re-start R and install again. This may take a couple of iterations.
Jason

**Comment by jasonleebrown** [comment]
p.s. let me know if you have any issues or successes here.  Thanks for your interests in Humboldt!

**Comment by mgaynor1** [comment]
This was actually a simple fix on my end. After reinstalling tcl-tk using homebrew - it started working. 
`brew install tcl-tk`
